app = "listygifty-web-prod"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    NEXT_PUBLIC_API_URL = "https://api.listygifty.com"
    NEXT_PUBLIC_APP_URL = "https://listygifty.com"

[env]
  NODE_ENV = "production"
  PORT = "8080"
  NEXT_TELEMETRY_DISABLED = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  timeout = "5s"
  path = "/"
