config:
  gcp:project: listygifty
  gcp:region: us-central1
  niftygifty:environment: production
  niftygifty:apiService: listygifty-api-prod
  niftygifty:webService: listygifty-web-prod
  niftygifty:migrationJob: listygifty-migrate-prod
  niftygifty:webServiceAccountName: niftygifty-runner
  niftygifty:secretPrefix: niftygifty-
  niftygifty:railsKeySecret: listygifty-rails-key-prod
  niftygifty:appDomain: listygifty.com
  niftygifty:apiDomain: api.listygifty.com
  niftygifty:wwwDomain: www.listygifty.com
  niftygifty:apiMinInstances: "1"
  niftygifty:apiMaxInstances: "10"
  niftygifty:apiConcurrency: "10"
  niftygifty:webMinInstances: "1"
  niftygifty:webMaxInstances: "10"
  niftygifty:webConcurrency: "80"
  niftygifty:apiPort: "3000"
  niftygifty:webPort: "8080"
  niftygifty:sqlInstance: niftygifty-postgres-central
  niftygifty:imageRegistry: gcr.io/listygifty
  niftygifty:apiImageRepo: niftygifty-api
  niftygifty:webImageRepo: listygifty-web
  niftygifty:androidAppLinkSha256CertFingerprints: ""
  niftygifty:sourceSha: ba4c47a86d8d
encryptionsalt: v1:Y6Pp500F2p4=:v1:SDeV4cgIvjehJdaa:/4eiMdddKoF97Shyjzle4BiFZnl7Qg==
